// <auto-generated />
using System;
using GraphQLFirst.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLFirst.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLFirst.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f34b4fdf-759c-4dba-9112-b9bfb8fbfe08"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("f9f88d26-3ac9-4248-adb3-754ddb37a811"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c6fba3c6-dca7-4fa8-a003-cfc566faccf5"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("f9f88d26-3ac9-4248-adb3-754ddb37a812"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a20ec81c-95bd-4ade-9432-74528744690d"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("f9f88d26-3ac9-4248-adb3-754ddb37a812"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQLFirst.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f88d26-3ac9-4248-adb3-754ddb37a811"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("f9f88d26-3ac9-4248-adb3-754ddb37a812"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQLFirst.Entities.Account", b =>
                {
                    b.HasOne("GraphQLFirst.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphQLFirst.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
